services:
  - type: web
    name: cicd-books-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
